image: golang:latest

stages:
  - lint
  - test
  - build

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - golangci-lint --version
  - go install github.com/uudashr/gocognit/cmd/gocognit@latest
  - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

  - make deps

lint:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - make test-unit

compile:
  stage: build
  script:
    - make build