image: golang:latest

stages:
  - test
  - build

before_script:
  - if [ ! -f /go/bin/goose ]; then go install github.com/pressly/goose/v3/cmd/goose@latest; fi
  - if [ ! -f /go/bin/mockgen ]; then go install github.com/golang/mock/mockgen@v1.6.0; fi
  - if [ ! -f /go/bin/golangci-lint ]; then go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest; fi
  - if [ ! -f /go/bin/gocognit ]; then go install github.com/uudashr/gocognit/cmd/gocognit@latest; fi
  - if [ ! -f /go/bin/gocyclo ]; then go install github.com/fzipp/gocyclo/cmd/gocyclo@latest; fi

  - make deps

test:
  stage: test
  script:
    - make test-unit

compile:
  stage: build
  script:
    - make build