image: golang:latest

stages:
  - test
  - build

services:
  - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /go/pkg/mod
    - /go/bin
    - go.sum
    - go.mod

before_script:
  - apt-get update && apt-get install -y docker.io
  - apt-get update && apt-get install -y docker-compose

  - docker system prune -a
  - docker volume prune

  - if [ ! -f /go/bin/goose ]; then go install github.com/pressly/goose/v3/cmd/goose@latest; fi
  - if [ ! -f /go/bin/mockgen ]; then go install github.com/golang/mock/mockgen@v1.6.0; fi
  - if [ ! -f /go/bin/golangci-lint ]; then go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest; fi
  - if [ ! -f /go/bin/gocognit ]; then go install github.com/uudashr/gocognit/cmd/gocognit@latest; fi
  - if [ ! -f /go/bin/gocyclo ]; then go install github.com/fzipp/gocyclo/cmd/gocyclo@latest; fi

  - make deps

variables:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: testdb
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

test:
  stage: test
  script:
    - make db
    - make test

compile:
  stage: build
  script:
    - make build