image: golang:latest

stages:
  - lint
  - test
  - build

# services:
#   - name: postgres:latest
#     alias: postgres

before_script:
  - if [ ! -f /go/bin/gomock ]; then go install github.com/gojuno/minimock/v3/cmd/minimock@latest; fi
  - if [ ! -f /go/bin/golangci-lint ]; then go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest; fi
  - if [ ! -f /go/bin/gocognit ]; then go install github.com/uudashr/gocognit/cmd/gocognit@latest; fi
  - if [ ! -f /go/bin/gocyclo ]; then go install github.com/fzipp/gocyclo/cmd/gocyclo@latest; fi
  - make deps
  - cd build && make
   


variables:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: testdb
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

lint:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - make test

compile:
  stage: build
  script:
    - make build