// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/api.proto

package api

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TPackagingType int32

const (
	TPackagingType_default TPackagingType = 0
	TPackagingType_bag     TPackagingType = 1
	TPackagingType_box     TPackagingType = 2
	TPackagingType_film    TPackagingType = 3
)

// Enum value maps for TPackagingType.
var (
	TPackagingType_name = map[int32]string{
		0: "default",
		1: "bag",
		2: "box",
		3: "film",
	}
	TPackagingType_value = map[string]int32{
		"default": 0,
		"bag":     1,
		"box":     2,
		"film":    3,
	}
)

func (x TPackagingType) Enum() *TPackagingType {
	p := new(TPackagingType)
	*p = x
	return p
}

func (x TPackagingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TPackagingType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (TPackagingType) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x TPackagingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TPackagingType.Descriptor instead.
func (TPackagingType) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type TOrderStatus int32

const (
	TOrderStatus_nil        TOrderStatus = 0
	TOrderStatus_accepted   TOrderStatus = 1
	TOrderStatus_expired    TOrderStatus = 2
	TOrderStatus_issued     TOrderStatus = 3
	TOrderStatus_returned   TOrderStatus = 4
	TOrderStatus_withdrawed TOrderStatus = 5
)

// Enum value maps for TOrderStatus.
var (
	TOrderStatus_name = map[int32]string{
		0: "nil",
		1: "accepted",
		2: "expired",
		3: "issued",
		4: "returned",
		5: "withdrawed",
	}
	TOrderStatus_value = map[string]int32{
		"nil":        0,
		"accepted":   1,
		"expired":    2,
		"issued":     3,
		"returned":   4,
		"withdrawed": 5,
	}
)

func (x TOrderStatus) Enum() *TOrderStatus {
	p := new(TOrderStatus)
	*p = x
	return p
}

func (x TOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[1].Descriptor()
}

func (TOrderStatus) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[1]
}

func (x TOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TOrderStatus.Descriptor instead.
func (TOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

type TOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID         int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Status         TOrderStatus           `protobuf:"varint,3,opt,name=Status,proto3,enum=NApi.TOrderStatus" json:"Status,omitempty"`
	AcceptTime     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=AcceptTime,proto3" json:"AcceptTime,omitempty"`
	ExpireTime     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
	IssueTime      *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=IssueTime,proto3" json:"IssueTime,omitempty"`
	Weight         float64                `protobuf:"fixed64,7,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Cost           string                 `protobuf:"bytes,8,opt,name=Cost,proto3" json:"Cost,omitempty"`
	Packaging      TPackagingType         `protobuf:"varint,9,opt,name=Packaging,proto3,enum=NApi.TPackagingType" json:"Packaging,omitempty"`
	ExtraPackaging TPackagingType         `protobuf:"varint,10,opt,name=ExtraPackaging,proto3,enum=NApi.TPackagingType" json:"ExtraPackaging,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TOrder) Reset() {
	*x = TOrder{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOrder) ProtoMessage() {}

func (x *TOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOrder.ProtoReflect.Descriptor instead.
func (*TOrder) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *TOrder) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TOrder) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *TOrder) GetStatus() TOrderStatus {
	if x != nil {
		return x.Status
	}
	return TOrderStatus_nil
}

func (x *TOrder) GetAcceptTime() *timestamp.Timestamp {
	if x != nil {
		return x.AcceptTime
	}
	return nil
}

func (x *TOrder) GetExpireTime() *timestamp.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

func (x *TOrder) GetIssueTime() *timestamp.Timestamp {
	if x != nil {
		return x.IssueTime
	}
	return nil
}

func (x *TOrder) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *TOrder) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *TOrder) GetPackaging() TPackagingType {
	if x != nil {
		return x.Packaging
	}
	return TPackagingType_default
}

func (x *TOrder) GetExtraPackaging() TPackagingType {
	if x != nil {
		return x.ExtraPackaging
	}
	return TPackagingType_default
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x04NApi\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n" +
	"\x06TOrder\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12*\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x12.NApi.TOrderStatusR\x06Status\x12:\n" +
	"\n" +
	"AcceptTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"AcceptTime\x12:\n" +
	"\n" +
	"ExpireTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ExpireTime\x128\n" +
	"\tIssueTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tIssueTime\x12\x16\n" +
	"\x06Weight\x18\a \x01(\x01R\x06Weight\x12\x12\n" +
	"\x04Cost\x18\b \x01(\tR\x04Cost\x122\n" +
	"\tPackaging\x18\t \x01(\x0e2\x14.NApi.TPackagingTypeR\tPackaging\x12<\n" +
	"\x0eExtraPackaging\x18\n" +
	" \x01(\x0e2\x14.NApi.TPackagingTypeR\x0eExtraPackaging*9\n" +
	"\x0eTPackagingType\x12\v\n" +
	"\adefault\x10\x00\x12\a\n" +
	"\x03bag\x10\x01\x12\a\n" +
	"\x03box\x10\x02\x12\b\n" +
	"\x04film\x10\x03*\\\n" +
	"\fTOrderStatus\x12\a\n" +
	"\x03nil\x10\x00\x12\f\n" +
	"\baccepted\x10\x01\x12\v\n" +
	"\aexpired\x10\x02\x12\n" +
	"\n" +
	"\x06issued\x10\x03\x12\f\n" +
	"\breturned\x10\x04\x12\x0e\n" +
	"\n" +
	"withdrawed\x10\x05B1Z/gitlab.ozon.dev/timofey15g/homework/pkg/api;apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_api_proto_goTypes = []any{
	(TPackagingType)(0),         // 0: NApi.TPackagingType
	(TOrderStatus)(0),           // 1: NApi.TOrderStatus
	(*TOrder)(nil),              // 2: NApi.TOrder
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_api_proto_depIdxs = []int32{
	1, // 0: NApi.TOrder.Status:type_name -> NApi.TOrderStatus
	3, // 1: NApi.TOrder.AcceptTime:type_name -> google.protobuf.Timestamp
	3, // 2: NApi.TOrder.ExpireTime:type_name -> google.protobuf.Timestamp
	3, // 3: NApi.TOrder.IssueTime:type_name -> google.protobuf.Timestamp
	0, // 4: NApi.TOrder.Packaging:type_name -> NApi.TPackagingType
	0, // 5: NApi.TOrder.ExtraPackaging:type_name -> NApi.TPackagingType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
